apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
      - name: html-app
        image: dante97/html-app
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: html-app
spec:
  selector:
    app: html-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort

